global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node_exporter
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ["traefik:8080"]
    scheme: http
    metrics_path: /metrics
  - job_name: "auth"
    static_configs:
      - targets: ["auth:3001"]
    metrics_path: auth/metrics
    basic_auth:
      username: 'prometheus'
      password: 'qwerty'
